### ISSUE TITLE
Error while executing command.

### ISSUE THREAD

**Issue by vinitchopra12** [elements-at/ProcessManager#112]
Hello,

When I execute the Process manager command, I get below error:

![image](https://user-images.githubusercontent.com/14720025/131783551-60fb9005-ca95-4d69-94e5-5559d6a1b6fd.png)

Below is the configuration I have created in Process Manager:

![image](https://user-images.githubusercontent.com/14720025/131783536-e3cecb52-fd2a-416a-8a0c-c114ec385c74.png)

Please assist me in resolving this issue. Also, please correct if anything I did wrong here.

**Comment by ckogler-elements** [comment]
Hi,
the issue is related to nginx. In https://github.com/elements-at/ProcessManager/blob/master/src/Model/MonitoringItem.php there is the method "isAlive" which checks if a Process with the given PID-Number is running. As posix_getpgid() seems to be not available in nginx we would need an alternative. Currently i don't know how to do it on nginx and i dont have a test environment :-(.

So the question is: How can we check if a process with a given id is running on nginx....
