### ISSUE TITLE
How to use log correctly?

### ISSUE THREAD

**Issue by valentin-** [elements-at/ProcessManager#130]
Hi, I'm using the extension in Pimcore X, it's working great so far.

Logging data with `$monitoringItem->getLogger()`, but `var/log/process-manager` ist empty and the column in the backend as well.
![image](https://user-images.githubusercontent.com/90033/144198273-7bc96cf3-582a-4662-a0cb-90f1c3f57565.png)

Is this a bug or am I using the logger wrong?

Thanks!

**Comment by ckogler-elements** [comment]
Hi,

you can define the logger in the settings tab - most of the time i use this settings
![image](https://user-images.githubusercontent.com/8791970/144210017-4f104dcd-d209-4f10-b4f5-80677b8fddfd.png)
If the job is executed via the pimcore admin (or by a cronjob which is defined in the "settings" tab) you should see a Icon appears in the log column.

I guess in your case the process is started manually or via a cronjob in the crontab - because of the "System" User. 

In this case you would have to define the logger in your command... because we don't have access to a config in this case...

E.g.
`

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $this->monitoringItem = $this->initProcessManager($input->getOption('monitoring-item-id'), ['autoCreate' => true,
            "loggers" => [
                [
                    'logLevel' => 'DEBUG',
                    'simpleLogFormat' => 'on',
                    'class' => '\Elements\Bundle\ProcessManagerBundle\Executor\Logger\Console'
                ],
                [
                    'logLevel' => 'DEBUG',
                    'simpleLogFormat' => 'on',
                    'class' => '\Elements\Bundle\ProcessManagerBundle\Executor\Logger\File'
                ]
            ]
        ]);
}

`

Regards,
Christian

**Comment by valentin-** [comment]
Thanks for the clarification, works as suggested.
