### ISSUE TITLE
Execute with Pimcore maintenance job

### ISSUE THREAD

**Issue by BlackbitDevs** [elements-at/ProcessManager#133]
Why was the option to execute process manager jobs with Pimcore's maintenance job removed in v4? This had the advantage that not necessarily a system admin had to set up an additional cronjob after plugin installation. Now a developer installs the bundle and has to notify the sysadmin to create the `process-manager:maintenance` cronjob because every client has a different environment / operating system how to set up cronjobs.

What is the advantage now? Because there already was the option to use a separate command if someone wants to execute process manager jobs more often than Pimcore maintenance.

**Comment by ckogler-elements** [comment]
Hi,
the problem was that it was not working 100% correctly in some cases. E.g. when the pimcore maintenance hanged or crashed before the Processmanager maintenance task was executed, nobody got e-mails that commands died...
 
So in our use case it was not a big deal to set up the extra cronjob because we developers set up the extra cronjob... but i fully understand you. Maybe we should add the option again, but set it to "false" by default? So the developer can enable it?

Pull requests are welcome ;-)

Regards,
Christian
