### ISSUE TITLE
feature: support deploying configurations

### ISSUE THREAD

**Issue by passioneight** [elements-at/ProcessManager#156]
When configuring the process manager (i.e., using the UI to add menu entries for the client), it would be nice if we could deploy the configuration, so we don't have to configure the same processes for every environment (i.e., dev, staging, prod).

Maybe we should create `YAML` files when adding a new configuration (and update them if the configuration changes).

If we introduce an additional flag to (multi-)select the environments as well, we could even have configurations based on the environment.

> No selection would mean _all_ environments, the selected ones otherwise. 

Wdyt?

**Comment by passioneight** [comment]
@ctippler wdyt?

**Comment by ctippler** [comment]
Well, i personally don't have the need for it because i just export/import the setting with HeidiSQL and most of the time the configurations are not identically, but i know that some guys would like to have the configurations in .yaml - others in the Database :-) . 
So maybe the best way would be to make it configurabale. 

Like Pimcore does it with the  e.g. PIMCORE_WRITE_TARGET_DOCUMENT_TYPES / PIMCORE_CONFIG_STORAGE_DIR_DOCUMENT_TYPES  .... https://github.com/pimcore/pimcore/blob/11.x/doc/Development_Documentation/21_Deployment/03_Configuration_Environments.md

e.g ELEMENTS_PROCESSMANAGER_WRITE_TARGET_CONFIGURATION  / ELEMENTS_PROCESSMANAGER_STORAGE_DIR_CONFIG
could be used to configure it.

Best regards

**Comment by passioneight** [comment]
@ctippler yes that makes sense. Can you provide a simple example of non-identical configurations, so, I can get a better idea of the available use cases?

**Comment by passioneight** [comment]
Awesome, thanks, I'll have a look soon :-)

**Comment by passioneight** [comment]
It's not really what I expected, but I confirm that it works :-)
