### ISSUE TITLE
Bugfix report email 

### ISSUE THREAD

**Issue by ckogler-elements** [elements-at/ProcessManager#18]
Only the first recipient got the info email

**Comment by AlternateIf** [comment]
this should be resolved by your recent commit. (https://github.com/elements-at/ProcessManager/commit/3a731d446abf5bec8667d5b1d7ef755a013a3947) 
Right @putzflorian?

**Comment by AlternateIf** [comment]
the default processmanager config uses an array for recipients.  the commit above made the maintenance fail upon the default config since it deliveres an array and no semicolon separated string. 

To resolve this and support both 'semicolon separated strings' and 'php arrays' in `$config['email']['recipients']` I made following changes: https://github.com/elements-at/ProcessManager/commit/658c8f63bb6cfc2c67c16fc90cececc9058466c1
