### ISSUE TITLE
process manager issue when upgraded to 5.0.0 version

### ISSUE THREAD

**Issue by Thejaswini-Rao-U** [elements-at/ProcessManager#192]
Hi Team

I have updated process manger version to 5.0.0, used pimcore 11, but got below error while migrating , type error

i tried installing 5.0.3 and 5.0.4 version but no luck still same error exists.

please help me to solve this issue, im stuck from few days in this issue.

![monitor1Error](https://github.com/elements-at/ProcessManager/assets/78895325/e237c41e-ad70-4f58-9946-06e1b6cbba1a)

**Comment by APochmann** [comment]
Don't have a solution for you but some remarks which might help you figuring out what's the problem:

Migration script [Version20230425000002.php](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Migrations/Version20230425000002.php) was intended to update all stored actions with new option `executeAtStates` on upgrade to v4.3.0. At that time (all versions 4.x.x) matadata was saved as string.
Since version 5.0.0 metadata is handled as an array but the DAO functions should take care of the conversion by implementing a function `convertDataFromRecourse` in [MonitoringItem/Dao.php](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Model/MonitoringItem/Dao.php#L124).

The error viible in your screenshot is most likely happening when the  [Version20230425000002.php](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Migrations/Version20230425000002.php) script tries to save a modified `MonitoringItem` which has actions defined.

I assume you started your update to 5.x from a version < 4.3 and in this case the migration scripts loops over all monitoring items which are loaded, checked for Actions, updated if neccessary and saved in case of changes.

The problem seems to be on loading the MonitoringItems: These are loaded via `MonitoringItem\Listing` objects `load()` method (effective in [MonitoringItem/Listing/Dao.php](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Model/MonitoringItem/Listing/Dao.php#L57)). This `load()` method loops over all found ids  and calls static function `MonitoringItem::getById` ([code](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Model/MonitoringItem.php#L264)). This function uses [MonitoringItem/Dao.php](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Model/MonitoringItem/Dao.php) which inherits `getById` from [AbstractDao.php](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Model/Dao/AbstractDao.php#L73) and defines `convertDataFromRecourse` locally in [MonitoringItem/Dao.php](https://github.com/elements-at/ProcessManager/blob/d424497029e4a2fb872cfe32223b3b0cc7708c3b/src/Model/MonitoringItem/Dao.php#L124). If `convertDataFromRecourse` is executed for each item, there should not be any issue on save as the metadata JSON string is converted into the required array. But somehow this mechanism seems to fail in your case as the error shows that metadata is still a string.

**Comment by ctippler** [comment]
Hi,

APochmann explained it quite well, so if you follow his explanations you should be able to locate the Problem and fix it. As i already mentioned in the Pimcore Theread - i can't reproduce it so it's hard to provide specific instructions.

Simple fix would be to delete all entries from plugin_process_manager_monitoring_item DB-Table. You will loose the log entries, but most of the time they aren't that important. The the migration should run through without any issue.

Regards,
Christian

**Comment by Thejaswini-Rao-U** [comment]
@APochmann @ctippler 
thanks for the solution, i have deleted entries from the table bundle_process_manager_monitoring_item;
now it got successfull migration

**Comment by NiklasBr** [comment]
I encountered this error when upgrading from Process Manager from 4.3.8 to 5.0.4 during a Pimcore 11 migration, when running `doctrine:migrations:migrate`.

```
[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20220829132224 failed during Execution. Error: "An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'"

In ExceptionConverter.php line 67:

  An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'


In Exception.php line 28:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'


In Statement.php line 130:

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'type' in 'field list'
```
