### ISSUE TITLE
Add Datadefinitions process not showing up

### ISSUE THREAD

**Issue by tbohus** [elements-at/ProcessManager#55]
Is the support of Datadefinitions plugin process abandoned or just not showing up in the newest version?

**Comment by ckogler-elements** [comment]
Hi, 
what do you mean with "Datadefinitions plugin process"?

regards,
Christian

**Comment by tbohus** [comment]
![Screen Shot 2020-09-24 at 16 27 21](https://user-images.githubusercontent.com/71832383/94158750-0d910480-fe83-11ea-8270-1cfccb881f33.png)

Sorry for not being clear. Here used to be a line where you could add Import definition process or Export definition process from the w-vision DataDefinitions bundle.

**Comment by ckogler** [comment]
Hi,
might it be that you intended to use this ProcessManager Bundle https://github.com/dpfaffenbauer/ProcessManager from dpfaffenbauer?
This ProcessManager Bundle (elements-at/ProcessManager) doesn't do anything with the w-vision DataDefinitions bundle... 

It's a little bit confusing because it seems that both bundles actually do the same thing...

Regards,
Christian

**Comment by tbohus** [comment]
I'm sorry, but it's a bit confusing with the same name and also the design seems to be very similar.

Thank you!
