### ISSUE TITLE
Remove process manager config permission and only allow admin users to make configurations

### ISSUE THREAD

**Issue by fashxp** [elements-at/ProcessManager#83]
with config permission a (non-admin) user could execute any command of pimcore, with might be a potential security risk

**Comment by ckogler-elements** [comment]
The issue is that some clients (non admin users) are setting up the jobs by them self so non-admin users have to be able to configure it. 
In V4.x we implemented a "command validator" https://github.com/elements-at/ProcessManager/blob/master/doc/commandsValidator.md
which by default only returns jobs which implements the "Elements\Bundle\ProcessManagerBundle\ExecutionTrait" .
So by default not all jobs are showing up. I hope thats fine for you?
