### ISSUE TITLE
Pimcore Command with extension prevent command execution

### ISSUE THREAD

**Issue by ITspirit** [elements-at/ProcessManager#9]
When i create a job to run a pimcore-command (from an bundle - in this case "enqueue:consume") the process manager add to the command line 

"--monitoring-item-id=174"

This will break the command with:

The "--monitoring-item-id" option does not exist.

Not sure if it works with "normal" pimcore-commands, but these one breaks. Only solution - call the command via cronjob (not seen, not monitored).

Maybe it would be fine to omit these "monitoring-item-id" on request on specific commands?

**Comment by ckogler-elements** [comment]
Hi,

i just refactored the script execution so that the --monitoring-item-id is only passed if the Command supports the parameter. 

If the parameter is not supported we use a fallback (we pass a system environment variable instead of the "monitoring-item-id" parameter and grab it later on...). Hacky, but it seems to work quite well.
 
Could you please check if it is working in your use case (latest releas)?

**Comment by ITspirit** [comment]
Hi,

just tested - works like a charm :+1: 

Thanks for the really fast change.
